### ISSUE TITLE
Описание настройки - вроде надо редактировать JSON

### ISSUE THREAD

**Issue by janvarev** [timhok/IreneVA-hassio-script-trigger-plugin#1]
Прочитал описание настройки плагина.

Если правильно понял код, то правильней не
> Откройте файл plugin_hassio_script_trigger.py в текстовом редакторе

а

> Запустите Ирину с плагином один раз, чтобы создался файл настроек плагина
> После этого зайдите в options/plugin_hassio_script_trigger.json и установите url и key

А вообще очень круто!

**Comment by timhok** [comment]
Поправил, спасибо!
